---
title: "Project 3"
author: "Cassandra Chou"
date: "2024-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r backgroundsetup}
library("here")
rds_files <- c("b_lyrics.RDS", "ts_lyrics.RDS", "sales.RDS")
## Check whether we have all 3 files
if (any(!file.exists(here("data", rds_files)))) {
    ## If we don't, then download the data
    b_lyrics <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/beyonce_lyrics.csv")
    ts_lyrics <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/taylor_swift_lyrics.csv")
    sales <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-29/sales.csv")

    ## Then save the data objects to RDS files
    saveRDS(b_lyrics, file = here("data", "b_lyrics.RDS"))
    saveRDS(ts_lyrics, file = here("data", "ts_lyrics.RDS"))
    saveRDS(sales, file = here("data", "sales.RDS"))
}

b_lyrics <- readRDS(here("data", "b_lyrics.RDS"))
ts_lyrics <- readRDS(here("data", "ts_lyrics.RDS"))
sales <- readRDS(here("data", "sales.RDS"))

library(lubridate)
library(stringr)
library(tidyverse)

```

## Problem 1
### part a)
```{r part1a}
sales_1a <- sales %>% mutate(released = mdy(str_remove(released, "(\\([A-Z]+\\))(\\[\\d+\\])")), country = fct_collapse(factor(country), "World" = c("World", "WW"), "FRA" = c("FRA", "FR")), sales = sales/1000000) %>% filter(country == "World" | country == "US" | country == "UK")

sales_1a

```


### part b)
```{r part1b}
sales_1b <- sales_1a %>% filter(country == "US") %>% mutate(years_since_release = floor((interval(released, Sys.Date()) / years(1)))) %>% group_by(artist)

sales_1b %>% summarise(recent = min(years_since_release), oldest = max(years_since_release), median = median(years_since_release))

```

### part c)
```{r part1c}
sales_1c <- sales_1a %>% group_by(artist, country) %>% summarise(total = sum(sales))
sales_1c

library(extrafont)

ggplot(sales_1c, aes(fill = country, y = total, x = artist)) + geom_bar(position = "fill", stat = "identity") + ylab("Percentage of Sales of Studio Albums (in millions)") + xlab("Artist") + labs(title = "Percentage of Sales of Taylor Swift and Beyoncé's Studio Albums by Country", subtitle = "World sales make up the highest percentage for both artists, followed by the US, then the UK") + guides(fill=guide_legend(title="Country")) + theme(plot.title = element_text(family = "Segoe UI Black", size = 16), axis.title.x = element_text(family = "Segoe UI Semilight"), axis.title.y = element_text(family = "Segoe UI Semilight"), plot.subtitle = element_text(family = "Segoe UI Semilight"), panel.background = element_rect(fill = "#fff1da"))

```


### part d)
```{r part1d}
sales_1d <- sales_1a %>% filter(country == "World") %>% mutate(title = as.factor(title))

ggplot(sales_1d, aes(x = sales, y = fct_reorder(title, sales), fill = artist)) + geom_bar(stat="identity") + xlab("Sales (in millions)") +
  ylab("Album Title") + labs(title = "Taylor Swift and Beyoncé's Global World Sales, Sorted by Album", subtitle = "Taylor Swift's Fearless Tops Worldwide Sales, Followed by Beyoncé's Dangerously\nin Love") +
  guides(fill=guide_legend(title="Artist")) +
  theme(plot.title = element_text(family = "Segoe UI Black", size = 12), 
        axis.title.x = element_text(family = "Segoe UI Semibold", size = 11), 
        axis.title.y = element_text(family = "Segoe UI Semibold", size = 11), 
        axis.text.x = element_text(family = "Segoe UI Semilight", size = 10), 
        axis.text.y = element_text(family = "Segoe UI Semilight", size = 10), 
        plot.subtitle = element_text(family = "Segoe UI Semilight"), 
        panel.background = element_rect(fill = "#fff1da"),
        legend.text = element_text(family = "Segoe UI Semilight", size = 10),
        legend.title = element_text(family = "Segoe UI Semibold", size = 11))

```

### part e)
```{r part1e}
ggplot(sales_1a, aes(x = released, y = sales, color = artist)) + geom_point() + facet_grid(vars(country), scales = "free_y") + xlab("Release Date") +
  ylab("Sales (in millions)") + labs(title = "Taylor Swift and Beyoncé's Album Sales by Release Date, sorted by Country", subtitle = "Albums Sales Overall Decreasing in US, UK, and Worldwide") + 
  guides(color=guide_legend(title="Artist")) +
  theme(plot.title = element_text(family = "Segoe UI Black", size = 12), 
        axis.title.x = element_text(family = "Segoe UI Semibold", size = 11), 
        axis.title.y = element_text(family = "Segoe UI Semibold", size = 11), 
        axis.text.x = element_text(family = "Segoe UI Semilight", size = 10), 
        axis.text.y = element_text(family = "Segoe UI Semilight", size = 10), 
        plot.subtitle = element_text(family = "Segoe UI Semilight"), 
        panel.background = element_rect(fill = "#faf1e5"),
        legend.text = element_text(family = "Segoe UI Semilight", size = 10),
        legend.title = element_text(family = "Segoe UI Semibold", size = 11),
        strip.background = element_rect(fill = "#dec3a4"))

ggplot(sales_1a, aes(x = released, y = sales, color = artist)) + geom_point() + facet_grid(vars(country)) + xlab("Release Date") +
  ylab("Sales (in millions)") + labs(title = "Taylor Swift and Beyoncé's Album Sales by Release Date, sorted by Country", subtitle = "Albums Sales Overall Decreasing in US, UK, and Worldwide") + 
  guides(color=guide_legend(title="Artist")) +
  theme(plot.title = element_text(family = "Segoe UI Black", size = 12), 
        axis.title.x = element_text(family = "Segoe UI Semibold", size = 11), 
        axis.title.y = element_text(family = "Segoe UI Semibold", size = 11), 
        axis.text.x = element_text(family = "Segoe UI Semilight", size = 10), 
        axis.text.y = element_text(family = "Segoe UI Semilight", size = 10), 
        plot.subtitle = element_text(family = "Segoe UI Semilight"), 
        panel.background = element_rect(fill = "#faf1e5"),
        legend.text = element_text(family = "Segoe UI Semilight", size = 10),
        legend.title = element_text(family = "Segoe UI Semibold", size = 11),
        strip.background = element_rect(fill = "#dec3a4"))

```


## Problem 2
### part a)
```{r part2a}
library(tidytext)

ts_lines <- ts_lyrics %>% unnest_tokens(output = line, input = Lyrics, token = "lines")
ts_hello <- ts_lines %>% filter(str_detect(line, "hello"))
ts_hello
ts_hello %>% count()
ts_goodbye <- ts_lines %>% filter(str_detect(line, "goodbye"))
ts_goodbye
ts_goodbye %>% count()

```
There are 6 Taylor Swift lines with "hello" and 12 Taylor Swift lines with "goodbye".

### part b)
```{r part2b}
b_hello <- b_lyrics %>% filter(str_detect(line, "hello"))
b_hello
b_hello %>% count()
b_goodbye <- b_lyrics %>% filter(str_detect(line, "goodbye"))
b_goodbye
b_goodbye %>% count()

```
Beyoncé has 32 lines with the word "hello" and 12 lines with the word "goodbye".

### part c)
```{r part2c}
library(wordcloud)
b_words <- b_lyrics %>% unnest_tokens(output = word, input = line, token = "words")
b_freq_words <- b_words %>% anti_join(stop_words) %>% count(word, sort = TRUE) %>% inner_join(get_sentiments("bing")) %>% head(25)
b_freq_words

ggplot(b_freq_words, aes(x = n, y = fct_reorder(word, n), fill = sentiment)) + geom_bar(stat="identity") +
  xlab("Frequency of Word (Count)") + ylab("Word") + labs(title = "25 Most Frequently Used Words in Beyoncé's Songs and their Frequencies,\nColored by Sentiment", subtitle = "Beyoncé's most frequently used word is love, but she uses a mix of positive and negative words") +
  guides(fill=guide_legend(title="Sentiment")) +
  theme(plot.title = element_text(family = "Segoe UI Black", size = 12), 
        axis.title.x = element_text(family = "Segoe UI Semibold", size = 11), 
        axis.title.y = element_text(family = "Segoe UI Semibold", size = 11), 
        axis.text.x = element_text(family = "Segoe UI Semilight", size = 10), 
        axis.text.y = element_text(family = "Segoe UI Semilight", size = 10), 
        plot.subtitle = element_text(family = "Segoe UI Semilight"), 
        panel.background = element_rect(fill = "#faf1e5"),
        legend.text = element_text(family = "Segoe UI Semilight", size = 10),
        legend.title = element_text(family = "Segoe UI Semibold", size = 11))

b_freq_words %>% with(wordcloud(word, n))
```

### part d)
```{r part2d}
ts_words <- ts_lines %>% unnest_tokens(output = word, input = line, token = "words")
ts_freq_word <- ts_words %>% anti_join(stop_words) %>% count(word, sort = TRUE) %>% inner_join(get_sentiments("bing")) %>% head(25)
ts_freq_word

ggplot(ts_freq_word, aes(x = n, y = fct_reorder(word, n), fill = sentiment)) + geom_bar(stat="identity") +
  xlab("Frequency of Word (Count)") + ylab("Word") + labs(title = "25 Most Frequently Used Words in Taylor Swift's Songs and their Frequencies,\nColored by Sentiment", subtitle = "Taylor Swift's most frequently used word is love, but she uses more negative than positive words") +
  guides(fill=guide_legend(title="Sentiment")) +
  theme(plot.title = element_text(family = "Segoe UI Black", size = 12), 
        axis.title.x = element_text(family = "Segoe UI Semibold", size = 11), 
        axis.title.y = element_text(family = "Segoe UI Semibold", size = 11), 
        axis.text.x = element_text(family = "Segoe UI Semilight", size = 10), 
        axis.text.y = element_text(family = "Segoe UI Semilight", size = 10), 
        plot.subtitle = element_text(family = "Segoe UI Semilight"), 
        panel.background = element_rect(fill = "#faf1e5"),
        legend.text = element_text(family = "Segoe UI Semilight", size = 10),
        legend.title = element_text(family = "Segoe UI Semibold", size = 11))

ts_freq_word %>% with(wordcloud(word, n))

```

### part e)
```{r part2e}




```








